name: Deploy Dockerized App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for Backend
        run: |
          cd server
          docker buildx build --push -t ${{ secrets.DOCKER_USERNAME }}/task-board-backend:latest .

      - name: Build and push Docker image for Frontend
        run: |
          cd client
          docker buildx build --push -t ${{ secrets.DOCKER_USERNAME }}/task-board-frontend:latest .

      - name: Deploy to server
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key user@ваш-сервер-ip '
            docker pull ${{ secrets.DOCKER_USERNAME }}/task-board-backend:latest && 
            docker pull ${{ secrets.DOCKER_USERNAME }}/task-board-frontend:latest && 
            docker run -d --rm --name backend-container -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/task-board-backend:latest && 
            docker run -d --rm --name frontend-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/task-board-frontend:latest
          '
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
